"""create canonical_entities table

Revision ID: 9287e3f98e3b
Revises: None
Create Date: 2026-08-31 01:51:50.061665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9287e3f98e3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('entity_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('reconciled_area_m2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflict_notes', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'unprocessed'"), nullable=False),
    sa.Column('centroid_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('centroid_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('idx_canonical_entities_geometry', 'canonical_entities', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_canonical_entities_geometry', table_name='canonical_entities', postgresql_using='gist')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
